<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"><div id="content">
  <div class="container-fluid">
    <div class="" style="margin-top:0%;">
      <div class="panel-body"> 
        <div class="row">
          <div class="col-md-12" id="printappend"><div class="row"><div class="col-md-12 text-center"><h3>CUSTOMER STATEMENT</h3></div><div class="col-md-12"><p style="margin-bottom:2px;"><strong>Store Name: </strong>WINE LAND</p><p style="margin-bottom:2px;"><strong>Store Address: </strong>894 RIVER DRIVE</p><p style="margin-bottom:2px;"><strong></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ELM WOOD, New Jersey 07407 </p><p style="margin-bottom:2px;"><strong>Store Phone: </strong>7327666018</p></div></div><br><div class="row" style="width:100%;"><div class="col-md-8 text-left" style="width:66%;display:inline-block;"><p style="margin-bottom:2px;"><strong>Drizly </strong></p><p style="margin-bottom:2px;"><strong></strong></p><p style="margin-bottom:2px;"><strong>,   </strong></p></div><div class="col-md-4" style="width:33%;display:inline-block;"><p style="margin-bottom:2px;"><strong>Date:</strong> January 30, 2019</p><p style="margin-bottom:2px;"><strong>Account:</strong> DRI67561</p><p style="margin-bottom:2px;"><strong>Phone:</strong> 201-773-6993</p></div></div><hr style="border-top:1px solid #999;"><table class="table table-bordered table-striped table-hover" style="border:none;"><thead><tr><th class="text-left">Tran. Date</th><th>Tran. Type</th><th class="text-right">Credit Amt.</th><th class="text-right">Debit Amt.</th><th class="text-right">Balance Amt.</th></tr></thead><tbody><tr><td class="text-left">01-26-2019</td><td>Purchase</td><td class="text-right">58.09</td><td class="text-right">0.00</td><td class="text-right">58.09</td></tr><tr><td class="text-left">01-26-2019</td><td>Purchase</td><td class="text-right">0.01</td><td class="text-right">0.00</td><td class="text-right">58.10</td></tr><tr><td class="text-left">01-26-2019</td><td>Purchase</td><td class="text-right">31.97</td><td class="text-right">0.00</td><td class="text-right">90.07</td></tr><tr><td class="text-left">01-26-2019</td><td>Purchase</td><td class="text-right">23.44</td><td class="text-right">0.00</td><td class="text-right">113.51</td></tr><tr><td class="text-left">01-27-2019</td><td>Purchase</td><td class="text-right">21.31</td><td class="text-right">0.00</td><td class="text-right">134.82</td></tr><tr><td class="text-left">01-27-2019</td><td>Purchase</td><td class="text-right">38.34</td><td class="text-right">0.00</td><td class="text-right">173.16</td></tr><tr><td class="text-left">01-27-2019</td><td>Purchase</td><td class="text-right">35.16</td><td class="text-right">0.00</td><td class="text-right">208.32</td></tr></tr></tbody></table>          
          </div>
        </div>
      </div>
    </div>
  </div>
</div>