INSERT INTO `mst_tax` (`vtaxcode`,`vtaxtype`,`ntaxrate`,`estatus`,`etransferstatus`,`Id`) VALUES ('TAX1','State',0.00,'Active','',1);
INSERT INTO `mst_tax` (`vtaxcode`,`vtaxtype`,`ntaxrate`,`estatus`,`etransferstatus`,`Id`) VALUES ('TAX2','Sales',0.00,'Active','',2);

INSERT INTO `kiosk_global_param` (`UId`,`ParameterName`,`ParameterValue`) VALUES (1,'kioskmedia','C:\\Work\\POS2020\\POS2020Kiosk\\Assets');
INSERT INTO `kiosk_global_param` (`UId`,`ParameterName`,`ParameterValue`) VALUES (2,'noactivitytimeout','10');
INSERT INTO `kiosk_global_param` (`UId`,`ParameterName`,`ParameterValue`) VALUES (3,'orderconfirmmsg','Thank you for your order.  Please visit  again!!');
INSERT INTO `kiosk_global_param` (`UId`,`ParameterName`,`ParameterValue`) VALUES (4,'showrevieworderpane','FALSE');

INSERT INTO `kiosk_page_master` (`PageId`,`InternalTitle`,`DisplayTitle`,`RowSize`,`ColumnSize`) VALUES (1,'NOT USED','NOT USED',0,0);
INSERT INTO `kiosk_page_master` (`PageId`,`InternalTitle`,`DisplayTitle`,`RowSize`,`ColumnSize`) VALUES (2,'NOT USED','NOT USED',0,0);
INSERT INTO `kiosk_page_master` (`PageId`,`InternalTitle`,`DisplayTitle`,`RowSize`,`ColumnSize`) VALUES (3,'NOT USED','NOT USED',3,4);
INSERT INTO `kiosk_page_master` (`PageId`,`InternalTitle`,`DisplayTitle`,`RowSize`,`ColumnSize`) VALUES (4,'NOT USED','NOT USED',3,4);
INSERT INTO `kiosk_page_master` (`PageId`,`InternalTitle`,`DisplayTitle`,`RowSize`,`ColumnSize`) VALUES (5,'Checkout','Checkout',4,5);

INSERT INTO `mst_synctable` VALUES (100,'kiosk_category',1,3,0),(101,'kiosk_default_ingredients',2,3,0),(102,'kiosk_global_param',3,3,0),(103,'kiosk_menu_header',4,3,0),(104,'kiosk_menu_item',5,3,0),(105,'kiosk_menu_item_options',6,3,0),(106,'kiosk_page_flow_detail',7,3,0),(107,'kiosk_page_flow_header',8,3,0),(108,'kiosk_page_master',9,3,0),(109,'kiosk_trn_order',10,3,0),(122,'mst_delete_table',7,3,0),(111,'web_store_settings',11,3,0),(117,'mst_ageverification',2,3,0),(116,'mst_adjustmentreason',1,3,0),(118,'mst_aisle',3,3,0),(119,'mst_category',4,3,0),(120,'mst_coupon',5,3,0),(121,'mst_customer',6,3,0),(123,'mst_department',8,3,0),(124,'mst_discount',9,3,0),(125,'mst_groupslabprice',10,3,0),(126,'mst_instantbook',11,3,0),(127,'mst_instantgame',12,3,0),(128,'mst_instantgameslot',13,3,0),(129,'mst_instantsettings',14,3,0),(130,'mst_instantslot',15,3,0),(131,'mst_item',16,3,0),(132,'mst_item_bucket',17,3,0),(133,'mst_item_size',18,3,0),(134,'mst_item_unit',19,3,0),(135,'mst_itemalias',20,3,0),(136,'mst_itemgroup',21,3,0),(137,'mst_itemkit',22,3,0),(138,'mst_itemlotmatrix',23,3,0),(139,'mst_itemmatrix',24,3,0),(140,'mst_itempackdetail',25,3,0),(141,'mst_itemslabprice',26,3,0),(142,'mst_itemvendor',27,3,0),(143,'mst_location',28,3,0),(144,'mst_missingitem',29,3,0),(145,'mst_paidout',30,3,0),(146,'mst_permission',31,3,0),(147,'mst_permissiongroup',32,3,0),(148,'mst_permissiongroupdetail',33,3,0),(149,'mst_posdevice',34,3,0),(150,'mst_printcustomamount',35,3,0),(151,'mst_shelf',36,3,0),(152,'mst_shelving',37,3,0),(153,'mst_size',38,3,0),(154,'mst_station',39,3,0),(155,'mst_store',40,3,0),(156,'mst_supplier',41,3,0),(157,'mst_tax',42,3,0),(158,'mst_template',43,3,0),(159,'mst_templatedetail',44,3,0),(160,'mst_tentertype',45,3,0),(161,'mst_unit',46,3,0),(162,'mst_unitconversion',47,3,0),(163,'mst_user',48,3,0),(164,'mst_warehouse',49,3,0),(165,'itemgroup',50,3,0),(166,'itemgroupdetail',51,3,0),(167,'trn_saleprice',52,3,0),(168,'trn_salepricedetail',53,3,0);

INSERT INTO `mst_item_unit` (`id`, `unit_name`) VALUES
(1, 'oz'),
(2, 'Liter'),
(3, '1/8 Barrel'),
(4, '1/6 Barrel'),
(5, '1/4 Barrel'),
(6, '1/2 Barrel'),
(7, 'mg'),
(8, 'gram'),
(9, 'kilogram'),
(10, 'lb');

INSERT INTO `mst_item_bucket` (`id`, `bucket_name`) VALUES
(1, '1/2 PT Can & Bottle (7 oz. - 8 0z)'),
(2, '1 PT Can & Bottle (8.1 oz. - 16 oz)'),
(3, '1 QT Can & Bottle (16.1 oz - 32 oz)'),
(4, 'Other OZ'),
(5, '1/8 Barrel'),
(6, '1/6 Barrel'),
(7, '1/4 Barrel'),
(8, '1/2 Barrel'),
(9, '3 Liter'),
(10, '5 Liter'),
(11, '5.7 Liter'),
(12, 'Other Liter'),
(13, 'Not Applicable');


INSERT INTO `mst_supplier` (`isupplierid`,`vsuppliercode`,`vcompanyname`,`vfnmae`,`vlname`,`vaddress1`,`vcity`,`vstate`,`vzip`,`vcountry`,`vphone`,`vemail`,`estatus`,`vvendortype`,`vvendorterm`,`icreditday`,`vsalesperson1`,`vsalesperson2`,`vsalesperson3`,`vsalesperson4`,`vsalesperson5`,`vsalesphone1`,`vsalesphone2`,`vsalesphone3`,`vsalesphone4`,`vsalesphone5`,`etransferstatus`,`vcode`,`vftpserver`,`vftpuser`,`vftppass`) VALUES (101,'101','General Vendor','--','--','--','--','--','--','USA','','p@com','Active','Vendor','COD',0,'--','','','','','','','','','',NULL,'General Vendor','','','');

INSERT INTO `mst_department` (`idepartmentid`,`vdepcode`,`vdepartmentname`,`vdescription`,`isequence`,`estatus`,`ionupload`,`etransferstatus`) VALUES (1,'1','General','',1,'Active',2,'2|1|');

INSERT INTO `mst_category` (`icategoryid`,`vcategorycode`,`vcategoryname`,`vdescription`,`vcategorttype`,`isequence`,`estatus`,`ionupload`,`etransferstatus`) VALUES (1,'1','General','General Sales','Sales',1,'Active',0,'2|1|');
INSERT INTO `mst_category` (`icategoryid`,`vcategorycode`,`vcategoryname`,`vdescription`,`vcategorttype`,`isequence`,`estatus`,`ionupload`,`etransferstatus`) VALUES (2,'2','Kiosk','Kiosk','Sales',2,'Active',0,'2|1|');

INSERT INTO `mst_warehouse` (`iid`,`vwhname`,`vwhcode`,`LastUpdate`) VALUES (101,'Warehouse 1','WH101','2000-01-01 00:00:00');

INSERT INTO `mst_permissiongroup` (`ipermissiongroupid`,`ipgroupid`,`vgroupname`,`estatus`,`etransferstatus`) VALUES (1,1,'Admin','Active',NULL);
INSERT INTO `mst_permissiongroup` (`ipermissiongroupid`,`ipgroupid`,`vgroupname`,`estatus`,`etransferstatus`) VALUES (2,1,'Manager','Active',NULL);
INSERT INTO `mst_permissiongroup` (`ipermissiongroupid`,`ipgroupid`,`vgroupname`,`estatus`,`etransferstatus`) VALUES (3,1,'Cashier','Active',NULL);

INSERT INTO `mst_tentertype` (`itenderid`,`vtendertype`,`estatus`,`vtendertag`,`etransferstatus`) VALUES (101,'Cash','Active','Cash','2|1|');
INSERT INTO `mst_tentertype` (`itenderid`,`vtendertype`,`estatus`,`vtendertag`,`etransferstatus`) VALUES (102,'Check','Active','Check','2|1|');
INSERT INTO `mst_tentertype` (`itenderid`,`vtendertype`,`estatus`,`vtendertag`,`etransferstatus`) VALUES (103,'Credit Card','Active','Credit','2|1|');
INSERT INTO `mst_tentertype` (`itenderid`,`vtendertype`,`estatus`,`vtendertag`,`etransferstatus`) VALUES (106,'Debit Card','Active','Debit','2|1|');
INSERT INTO `mst_tentertype` (`itenderid`,`vtendertype`,`estatus`,`vtendertag`,`etransferstatus`) VALUES (109,'EBT','Active','Ebt','2|1|');
INSERT INTO `mst_tentertype` (`itenderid`,`vtendertype`,`estatus`,`vtendertag`,`etransferstatus`) VALUES (120,'ReturnItem','Active','Cash','2|1|');
INSERT INTO `mst_tentertype` (`itenderid`,`vtendertype`,`estatus`,`vtendertag`,`etransferstatus`) VALUES (121,'Change','Active','Cash','2|1|');
INSERT INTO `mst_tentertype` (`itenderid`,`vtendertype`,`estatus`,`vtendertag`,`etransferstatus`) VALUES (122,'On Account','Active','OnAcct','2|1|');
INSERT INTO `mst_tentertype` (`itenderid`,`vtendertype`,`estatus`,`vtendertag`,`etransferstatus`) VALUES (124,'WIC Check','Active','Check','2|1|');

INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER001','MENU_ITEM','Item','','PER048',1,'Menu Item','1|',1);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER002','ADD_ITEM','Item','','PER048',1,'Add Item','1|',2);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER003','DELETE_ITEM','Item','','PER048',2,'Delete Item','1|',3);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER004','MENU_USER','User','','PER044',1,'Menu User','1|',4);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER005','ADD_USER','User','','PER044',1,'Add User','1|',5);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER006','DELETE_USER','User','','PER044',2,'Delete User','1|',6);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER007','MENU_GROUP','Group','','PER044',1,'Menu Group','1|',7);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER008','ADD_GROUP','Group','','PER044',1,'Add Group','1|',8);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER009','DELETE_GROUP','Group','','PER044',2,'Delete Group','1|',9);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER010','MENU_CATEGORY','Category','','PER028',1,'Menu Category','1|',10);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER011','ADD_CATEGORY','Category','','PER028',1,'Add Category','1|',11);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER012','DELETE_CATEGORY','Category','','PER028',2,'Delete Category','1|',12);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER013','MENU_DEPARTMENT','Department','','PER028',1,'Menu Department','1|',13);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER014','ADD_DEPARTMENT','Department','','PER028',1,'Add Department','1|',14);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER015','DELETE_DEPARTMENT','Department','','PER028',2,'Delete Department','1|',15);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER044','MENU_USERS','Users','','PER044',1,'Users','1|',16);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER045','MENU_ITEMGROUP','Item Group','','PER048',1,'Menu Item Group','1|',17);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER016','MENU_CUSTOMER','Customer','','PER016',1,'Menu Customer','1|',18);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER017','ADD_CUSTOMER','Customer','','PER016',1,'Add Customer','1|',19);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER018','DELETE_CUSTOMER','Customer','','PER016',2,'Delete Customer','1|',20);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER019','MENU_STORE','Store','','PER019',1,'Menu Store','1|',21);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER020','ADD_STORE','Store','','PER019',1,'Add Store','1|',22);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER021','DELETE_STORE','Store','','PER019',2,'Delete Store','1|',23);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER022','MENU_SUPPLIER','Supplier','','PER022',1,'Menu Supplier','1|',24);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER023','ADD_SUPPLIER','Supplier','','PER022',1,'Add Supplier','1|',25);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER024','DELETE_SUPPLIER','Supplier','','PER022',2,'Delete Supplier','1|',26);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER025','MENU_REGISTER','Register','','PER028',1,'Menu Register','1|',27);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER026','ADD_REGISTER','Register','','PER028',1,'Add Register','1|',28);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER027','DELETE_REGISTER','Register','','PER028',2,'Delete Register','1|',29);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER028','MENU_ADMINISTRATION','Administration','','PER028',1,'Menu Administration','1|',30);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER029','MENU_DISCOUNT','Discount','','PER048',1,'Menu Discount','1|',31);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER030','ADD_DISCOUNT','Discount','','PER048',1,'Add Discount','1|',32);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER031','DELETE_DISCOUNT','Discount','','PER048',2,'Delete Discount','1|',33);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER032','MENU_UNIT','Unit','','PER028',1,'Menu Unit','1|',34);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER033','ADD_UNIT','Unit','','PER028',1,'Add Unit','1|',35);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER034','DELETE_UNIT','Unit','','PER028',2,'Delete Unit','1|',36);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER035','MENU_UNITCONVERSION','Unit Conversion','','PER028',1,'Menu Unit Conversion','1|',37);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER036','ADD_UNITCONVERSION','Unit Conversion','','PER028',1,'Add Unit Conversion','1|',38);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER037','DELETE_UNITCONVERSION','Unit Conversion','','PER028',2,'Delete Unit Conversion','1|',39);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER038','MENU_TAX','Tax','','PER028',1,'Menu Tax','1|',40);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER039','ADD_TAX','Tax','','PER028',1,'Add Tax','1|',41);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER040','DELETE_TAX','Tax','','PER028',2,'Delete Tax','1|',42);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER041','MENU_TERMINALIMAGE',' Terminal Image','','PER028',1,'Menu Terminal Image','1|',43);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER042','ADD_TERMINALIMAGE',' Terminal Image','','PER028',1,'Add Terminal Image','1|',44);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER043','DELETE_TERMINALIMAGE',' Terminal Image','','PER028',2,'Delete Terminal Image','1|',45);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER046','ADD_ITEMGROUP','Item Group','','PER048',1,'Add Item Group','1|',46);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER047','DELETE_ITEMGROUP','Item Group','','PER048',2,'Delete Item Group','1|',47);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER048','MENU_ITEMS','Item Group','','PER048',1,'Item Group','1|',48);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER049','MENU_REPORT','Report','','PER049',1,'Report','1|',49);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER052','MENU_SALE','Sale','','PER048',1,'Menu Sale','1|',50);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER053','ADD_SALE','Sale','','PER048',2,'Add Sale','1|',51);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER054','DELETE_SALE','Sale','','PER048',3,'Delete Sale','1|',52);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER055','MENU_PAIDOUT','Paid Out','','PER028',1,'Menu Paid Out','1|',53);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER056','ADD_PAIDOUT','Paid Out','','PER028',2,'Add Paid Out','1|',54);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER057','DELETE_PAIDOUT','Paid Out','','PER028',3,'Delete Paid Out','1|',55);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER058','DESHBOARD_QUICKLINKS','Dashboard','','PER058',1,'Dashboard Quicklinks','1|',56);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER059','DESHBOARD_WEATHER','Dashboard','','PER059',2,'Dashboard Weather','1|',57);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER060','DESHBOARD_SALESBYDEPARTMENT_CHART','Dashboard','','PER060',3,'Sales By Department Chart','1|',58);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER061','DESHBOARD_SALESBYCATEGORY_CHART','Dashboard','','PER061',4,'Sales By Category Chart','1|',59);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER050','MENU_SETTING','Setting','','PER050',1,'Setting','1|',60);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER051','ADD_SETTING','Setting','','PER050',1,'Add Setting','1|',61);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER062','MENU_CUSTOMAMOUNT','Custom Amount','','PER028',1,'Custom Amount','1|',62);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00071','NT_NOSALE','Item','ACTION','',1,'No Sale','1|',63);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00072','NT_PAIDOUT','Item','ACTION','',1,'Paidout','1|',64);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00073','NT_CASHPICKUP','Item','ACTION','',2,'cash pickup','1|',65);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00074','NT_DELETEITEM','User','ACTION','',1,'Delete Item','1|',66);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00075','NT_DISCOUNT','User','ACTION','',1,'Discount','1|',67);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00076','NT_TAX','User','ACTION','',2,'Apply Tax','1|',68);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00077','NT_PRICEMATCH','Group','ACTION','',1,'Price Match','1|',69);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00078','NT_EDITUSER','Group','ACTION','',1,'Edit User','1|',70);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00079','NT_DELETEUSER','Group','ACTION','',2,'Delete User','1|',71);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00080','NT_SETTING','Group','ACTION','',2,'Setting','1|',72);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00081','NT_ZREPORT','Group','ACTION','',2,'Z Report','1|',73);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00082','NT_RETURNITEM','Group','ACTION','',2,'Return Item','1|',74);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00083','NT_VOID','Group','ACTION','',2,'Void Transaction','1|',75);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00084','NT_HOLD','Group','ACTION','',2,'Hold Transaction','1|',76);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00085','SHOWADMIN','Show Admin','','PER050',2,'Show admin','1|',78);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00086','NT_XREPORT','Group','ACTION','',2,'X Report','1|',79);
INSERT INTO `mst_permission` (`vpermissioncode`,`vpermissionname`,`vmenuname`,`vpermissiontype`,`vppercode`,`ivorder`,`vdesc`,`etransferstatus`,`Id`) VALUES ('PER00087','NT_PRICECHECK','Group','ACTION','',2,'Price Check','1|',80);

INSERT INTO `mst_user` (`iuserid`,`vfname`,`vlname`,`vaddress1`,`vaddress2`,`vcity`,`vstate`,`vzip`,`vcountry`,`vphone`,`vemail`,`vuserid`,`vpassword`,`vusertype`,`vpasswordchange`,`dfirstlogindatetime`,`dlastlogindatetime`,`estatus`,`vuserbarcode`,`dlockoutdatetime`,`vlocktype`,`etransferstatus`) VALUES (101,'Admin ','User','--','','','','','','','--','111','MTExMQ==','Admin','No','2012-08-08','2012-08-08','Active','99999999',NULL,'Unlock',NULL);
INSERT INTO `mst_user` (`iuserid`,`vfname`,`vlname`,`vaddress1`,`vaddress2`,`vcity`,`vstate`,`vzip`,`vcountry`,`vphone`,`vemail`,`vuserid`,`vpassword`,`vusertype`,`vpasswordchange`,`dfirstlogindatetime`,`dlastlogindatetime`,`estatus`,`vuserbarcode`,`dlockoutdatetime`,`vlocktype`,`etransferstatus`) VALUES (102,'Manager','User 12','--','','','','','','','--','999','OTk5OQ==','Manager','No','2012-07-12','2012-07-12','Active','',NULL,'',NULL);
INSERT INTO `mst_user` (`iuserid`,`vfname`,`vlname`,`vaddress1`,`vaddress2`,`vcity`,`vstate`,`vzip`,`vcountry`,`vphone`,`vemail`,`vuserid`,`vpassword`,`vusertype`,`vpasswordchange`,`dfirstlogindatetime`,`dlastlogindatetime`,`estatus`,`vuserbarcode`,`dlockoutdatetime`,`vlocktype`,`etransferstatus`) VALUES (103,'Cashier','User','--','','','','','','','--','333','MzMzMw==','Cashier','No','2011-07-12','2011-07-12','Active','',NULL,'Unlock',NULL);

insert into `mst_station`(`Id`,`StationName`) values (1,'KIOSK');
insert into `mst_station`(`Id`,`StationName`) values (2,'KITCHEN');
insert into `mst_station`(`Id`,`StationName`) values (3,'Delivery');

INSERT INTO `mst_paidout` (`vpaidoutname`, `estatus`) VALUES ('Milk', 'Active');
INSERT INTO `mst_paidout` (`vpaidoutname`, `estatus`) VALUES ('Utility', 'Active');
INSERT INTO `mst_paidout` (`vpaidoutname`, `estatus`) VALUES ('Supply', 'Active');

insert into `mst_ageverification` (`vname`,`vvalue`) values('None','0');
 
INSERT INTO `mst_unit` (`iunitid`,`vunitcode`,`vunitname`,`vunitdesc`,`estatus`) VALUES (1,'UNT001','Each','Each','Active');
INSERT INTO `mst_unit` (`iunitid`,`vunitcode`,`vunitname`,`vunitdesc`,`estatus`) VALUES (2,'UNT002','Pound','Pound','Active');


INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (1,'0','Standard','1','Bottle Deposit','UNT001','1','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','','','2016-10-12','No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,0,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (2,'0','Standard','2','Taxable Item','UNT001','2','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'Y','N','','','2016-10-19','No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,0,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (3,'0','Standard','3','Non Taxable Item','UNT001','3','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','','','2016-08-01','No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (4,'0','Standard','4','Conv. Charge (%)','UNT001','4','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','N','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','No',0.00,'Code 128',0.00,0.00,NULL,'2015-06-16',NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (5,'0','Standard','5','Conv. Charge ($)','UNT001','5','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','N','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','No',0.00,'Code 128',0.00,0.00,NULL,'2015-06-16',NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (6,'0','Standard','6','Lottery Redeem','UNT001','6','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (8,'0','Standard','8','Instant Lottery','UNT001','8','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','Y','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','No',0.00,'Code 128',0.00,0.00,NULL,'2014-05-06',NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (9,'0','Standard','9','Credit Payment','UNT001','9','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','N','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (13,'0','Standard','13','ACCOUNTING','UNT001','13','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','N','ACCOUNTING',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','No',0.00,'Code 128',0.00,0.00,NULL,'2015-03-03',NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (14,'0','Standard','14','BACKUP','UNT001','14','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','N','BACKUP',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','No',0.00,'Code 128',0.00,0.00,NULL,'2015-03-03',NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (15,'0','Standard','15','REPORTS','UNT001','15','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','N','REPORTS',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','No',0.00,'Code 128',0.00,0.00,NULL,'2015-03-03',NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (16,'0','Standard','16','Edit Permission Group','UNT001','16','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','N','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','No',0.00,'Code 128',0.00,0.00,NULL,'2015-08-28',NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (17,'0','Standard','17','Store Setting','UNT001','17','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (18,'0','Standard','18','Coupon','UNT001','18','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (20,'0','Standard','20','Lottery Sales','UNT001','20','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (21,'0','Standard','21','Instant Sales','UNT001','21','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (22,'0','Standard','22','Lottery Redeem','UNT001','22','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`) VALUES (23,'0','Standard','23','Instant Redeem','UNT001','23','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0);
INSERT INTO `mst_item` (`iitemid`,`webstore`,`vitemtype`,`vitemcode`,`vitemname`,`vunitcode`,`vbarcode`,`vpricetype`,`vcategorycode`,`vdepcode`,`vsuppliercode`,`iqtyonhand`,`ireorderpoint`,`dcostprice`,`dunitprice`,`nsaleprice`,`nlevel2`,`nlevel3`,`nlevel4`,`iquantity`,`ndiscountper`,`ndiscountamt`,`vtax1`,`vtax2`,`vfooditem`,`vdescription`,`dlastsold`,`visinventory`,`dpricestartdatetime`,`dpriceenddatetime`,`estatus`,`nbuyqty`,`ndiscountqty`,`nsalediscountper`,`vshowimage`,`itemimage`,`vageverify`,`ebottledeposit`,`nbottledepositamt`,`vbarcodetype`,`ntareweight`,`ntareweightper`,`dcreated`,`dlastupdated`,`dlastreceived`,`dlastordered`,`nlastcost`,`nonorderqty`,`vparentitem`,`nchildqty`,`vsize`,`npack`,`nunitcost`,`ionupload`,`nsellunit`,`ilotterystartnum`,`ilotteryendnum`,`etransferstatus`,`vsequence`,`vcolorcode`,`vdiscount`,`norderqtyupto`,`vshowsalesinzreport`,`iinvtdefaultunit`,`LastUpdate`) VALUES (10,'0','Standard','10','Bottle Deposit Redeem','UNT001','10','','1','1','101',0,NULL,0.0000,0.00,0.0000,0.00,0.00,0.00,0,0.00,0.00,'N','N','','',NULL,'No',NULL,NULL,'Active',0,0,0.00,'No',NULL,'','',0.00,'Code 128',0.00,0.00,NULL,NULL,NULL,NULL,0.00,0,'0',0.00,'',1,0.0000,2,1,0,0,'2|1|','0','None','Yes',0,'No',0,'2016-09-29 10:41:57');

INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (1,3,1.10);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (2,4,1.35);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (3,5,1.40);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (4,6,1.60);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (5,10,0.10);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (6,11,1.85);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (7,12,0.12);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (8,15,0.15);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (9,18,2.60);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (10,20,0.20);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (11,25,0.25);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (12,26,2.85);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (13,29,0.29);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (14,30,0.30);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (15,35,0.35);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (16,55,0.55);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (17,59,0.59);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (18,60,0.60);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (19,61,10.00);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (20,62,9.50);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (21,63,9.00);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (22,64,0.50);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (23,65,0.65);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (24,66,8.00);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (25,67,7.50);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (26,68,7.00);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (27,69,0.69);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (28,70,0.70);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (29,71,6.50);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (30,72,6.00);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (31,73,5.50);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (32,74,5.00);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (33,75,0.75);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (34,76,1.00);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (35,77,1.25);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (36,78,1.50);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (37,79,0.79);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (38,80,0.80);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (39,81,1.75);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (40,82,2.00);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (41,83,2.25);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (42,84,2.50);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (43,85,0.85);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (44,86,2.75);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (45,87,3.00);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (46,88,3.25);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (47,89,0.89);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (48,90,0.90);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (49,91,3.50);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (50,92,3.75);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (51,93,4.00);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (52,95,0.95);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (53,96,4.50);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (54,99,0.99);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (55,39,0.39);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (56,40,0.40);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (57,45,0.45);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (58,49,0.49);
INSERT INTO `mst_coupon` (`Id`,`CouponCode`,`CouponAmount`) VALUES (59,50,0.50);

INSERT INTO `kiosk_deli_order` (`DeliOrderId`) VALUES (0);